name: planning_poker_flutter
description: Clone do site Planning Poker
  [https://planningpokeronline.com/dU9BHlI0XvIsY5f4qfXg]

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  mocktail: ^0.3.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  stomp_dart_client: ^0.4.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
